#3337 Add public DID to bank invitaiton message
RTGS-OpenSource/rtgs-dotnet-sdk pull request #56
Opened 2022-02-21 15:47 UTC by maxoizs

#3337 Add public DID to bank invitaiton message

2022-02-22 17:32 UTC, Bassetts requested changes

2022-02-22 17:32 UTC, Bassetts commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.Publisher/RtgsConnectionBroker.cs
> +			var result = await _identityClient.Vault.GetPublicDID();
We are missing a test case for if `SendInvitationToRtgsAsync` succeeds but `GetPublicDid` fails.

2022-02-22 17:32 UTC, Bassetts commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.Publisher/RtgsConnectionBroker.cs
> +	private async Task<string> GetPublicDid()
This method name should be `GetIdCryptAgentPublicDidAsync`

2022-02-22 17:32 UTC, Bassetts commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.Publisher/RtgsConnectionBroker.cs
> +			_logger.LogError(ex, "Error occurred when calling ID Crypt Cloud Agent, to get PublicDID");
"Error occured sending GetPublicDid request to ID Crypt Cloud Agent"

We should update the `LogError` in `CreateIdCryptInvitationAsync` to mention `CreateInvitation` as well.

2022-02-22 17:32 UTC, Bassetts commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.Publisher/RtgsConnectionBroker.cs
> +		string publicDid,
This should be named `agentPublicDid`

2022-02-22 17:32 UTC, Bassetts commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.Publisher/RtgsConnectionBroker.cs
> +		try
Could we format the try/catch the same as `CreateIdCryptInvitationAsync` does it? Just having the `GetPublicDID` call inside the try?

2022-02-22 17:32 UTC, Bassetts commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.Publisher.IntegrationTests/TestData/IdCryptTestMessages.cs
> +	public static DIDCreated DIDCreated => new()
Could this be called `AgentPublicDidResponse`

2022-02-22 17:32 UTC, Bassetts commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.Publisher.IntegrationTests/TestData/IdCryptTestMessages.cs
> +	public static string PublicDIDResponseJson =>
and this `AgentPublicDidResponseJson`

2022-02-22 17:32 UTC, Bassetts commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.Publisher/Messages/IdCryptInvitationV1.cs
> +	public string AgentPublicDid { get; set; }
Should be `init`

2022-02-23 09:39 UTC, maxoizs commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.Publisher.IntegrationTests/TestData/IdCryptTestMessages.cs
> +	public static DIDCreated DIDCreated => new()
no, we shouldn't change that, it belongs IdCrypt no to us anyway.

2022-02-23 09:42 UTC, maxoizs commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.Publisher/RtgsConnectionBroker.cs
> +		try
I'll make `CreateIdCryptInvitationAsync` as same as this one no problem

2022-02-23 09:51 UTC, maxoizs commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.Publisher/RtgsConnectionBroker.cs
> +			_logger.LogError(ex, "Error occurred when calling ID Crypt Cloud Agent, to get PublicDID");
there is a typo in occurred, the below would be better. 
"Error occurred when sending GetPublicDid request to ID Crypt Cloud Agent"

2022-02-23 14:16 UTC, DavidRamsbottomRTGS commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.Publisher.IntegrationTests/HttpHandlers/StatusCodeHttpHandler.cs
> +		var response = new HttpResponseMessage(requestMock.HttpStatusCode)
Also - why are you using a dictionary to track the requests, and a list and .Where for this set of mocks?  Would it make more sense to use either dictionary for both, or list for both?

2022-02-23 14:18 UTC, DavidRamsbottomRTGS commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.Publisher.IntegrationTests/RtgsConnectionBrokerTests/GivenOpenConnection.cs
> +		};
Indentation appears incorrect

2022-02-23 14:19 UTC, Bassetts submitted a review, later dismissed

2022-02-23 14:19 UTC, Bassetts commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.Publisher.IntegrationTests/HttpHandlers/StatusCodeHttpHandler.cs
> +		var requestMock = _mockHttpResponses.FirstOrDefault(i => i.Path == request.RequestUri.LocalPath);
Should we use `Single` instead of `FirstOrDefault` here? I think we'd want to error if a matching request isn't in the list.

2022-02-23 14:19 UTC, Bassetts commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.Publisher.IntegrationTests/RtgsConnectionBrokerTests/GivenOpenConnection.cs
> +						Content = new StringContent ( IdCryptTestMessages.AgentPublicDidResponseJson ),
Some stray spaces around the call to the StringContent constructor

2022-02-23 14:21 UTC, DavidRamsbottomRTGS commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.Publisher.IntegrationTests/RtgsConnectionBrokerTests/GivenOpenConnection.cs
> +			var debugLogs = _serilogContext.ConnectionBrokerLogs(LogEventLevel.Debug).FirstOrDefault();
Think this is a regression - the test before was trying to check if there was one and one log only, this will just check if the first is correct.

2022-02-23 14:22 UTC, DavidRamsbottomRTGS commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.Publisher.IntegrationTests/RtgsConnectionBrokerTests/GivenOpenConnection.cs
> +				new ("Sent GetPublicDid request to ID Crypt Cloud Agent", LogEventLevel.Debug)
Is this correct?  If the API is down then will this last log message appear?

2022-02-23 14:27 UTC, maxoizs commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.Publisher.IntegrationTests/RtgsConnectionBrokerTests/GivenOpenConnection.cs
> +				new ("Sent GetPublicDid request to ID Crypt Cloud Agent", LogEventLevel.Debug)
yes, it does log the message, as we have seen IDCryptSDK doesn't handle bad requests so still will pass. as you mentioned we going to rewrite IDCryptSDK in the future, then we could make sure it throw on errors, and only return if successful

2022-02-23 14:27 UTC, DavidRamsbottomRTGS commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.Publisher.IntegrationTests/TestData/IdCryptTestMessages.cs
> +	public static DIDCreated DIDCreated => new()
Yea change the property name

2022-02-23 14:29 UTC, maxoizs commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.Publisher.IntegrationTests/RtgsConnectionBrokerTests/GivenOpenConnection.cs
> +			var debugLogs = _serilogContext.ConnectionBrokerLogs(LogEventLevel.Debug).FirstOrDefault();
I got your point.

2022-02-23 14:29 UTC, maxoizs commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.Publisher.IntegrationTests/RtgsConnectionBrokerTests/GivenOpenConnection.cs
> +						Content = new StringContent ( IdCryptTestMessages.AgentPublicDidResponseJson ),
sure I'll rerun dotnet format

2022-02-23 14:32 UTC, maxoizs commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.Publisher.IntegrationTests/HttpHandlers/StatusCodeHttpHandler.cs
> +		var response = new HttpResponseMessage(requestMock.HttpStatusCode)
the request was there already but because we handle more than one request I made it into a dictionary. 
if a request mock wasn't available, it wont to be handled, the handler doesn't pass any request to base class anyway so it'll fail regardless

2022-02-23 14:36 UTC, DavidRamsbottomRTGS commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.Publisher.IntegrationTests/HttpHandlers/StatusCodeHttpHandler.cs
> +		var response = new HttpResponseMessage(requestMock.HttpStatusCode)
But if you handle more than 1 request with the same URL it will error?  Don't see why a dictionary is better than a list and linq tbh

2022-02-23 14:42 UTC, DavidRamsbottomRTGS commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.Publisher.IntegrationTests/TestData/IdCryptTestMessages.cs
> +	public static DIDCreated DIDCreated => new()
I see what you mean but I don't think 'DIDCreated' is any more descriptive..

2022-02-23 14:46 UTC, maxoizs commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.Publisher.IntegrationTests/HttpHandlers/StatusCodeHttpHandler.cs
> +		var response = new HttpResponseMessage(requestMock.HttpStatusCode)
It won't error it'll override, and that's how it was before, so I don't want to change that

2022-02-23 14:48 UTC, DavidRamsbottomRTGS commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.Publisher.IntegrationTests/RtgsConnectionBrokerTests/GivenOpenConnection.cs
> +				new ("Sent GetPublicDid request to ID Crypt Cloud Agent", LogEventLevel.Debug)
The IDCryptSDK does throw an exception when it gets a 503, is this definitely working as you expect?

2022-02-23 14:56 UTC, DavidRamsbottomRTGS commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.Publisher.IntegrationTests/HttpHandlers/StatusCodeHttpHandler.cs
> +		var response = new HttpResponseMessage(requestMock.HttpStatusCode)
Ah yea fair enough, you're right.

2022-02-23 15:13 UTC, maxoizs commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.Publisher.IntegrationTests/RtgsConnectionBrokerTests/GivenOpenConnection.cs
> +				new ("Sent GetPublicDid request to ID Crypt Cloud Agent", LogEventLevel.Debug)
so we resolve here

2022-02-23 15:33 UTC, maxoizs commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.Publisher.IntegrationTests/TestData/IdCryptTestMessages.cs
> +	public static DIDCreated DIDCreated => new()
we going with GetPublicDidResponse

2022-02-23 16:07 UTC, merged