Add IdCryptCreateInvitationHandler (Introducing idea of InternalHandlers)
RTGS-OpenSource/rtgs-dotnet-sdk pull request #64
Opened 2022-03-16 15:53 UTC by DavidRamsbottomRTGS

2022-03-16 17:12 UTC, sichiu commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK/IdCrypt/IdCryptPublisher.cs
> +		_internalPublisher.SendMessageAsync(message, "idcrypt.invitation.tortgs.v1", cancellationToken);
@lewishenson Can you confirm what format we're going with for the message identifiers?

2022-03-17 09:34 UTC, lewishenson commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK/IdCrypt/IdCryptPublisher.cs
> +		_internalPublisher.SendMessageAsync(message, "idcrypt.invitation.tortgs.v1", cancellationToken);
Not yet but that looks ok for now. We've got another ticket to cover finalising the message identifiers.

2022-03-18 10:40 UTC, DavidRamsbottomRTGS commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK/Subscriber/Handlers/Internal/IInternalHandler.cs
> +internal interface IInternalHandler<TReceivedMessage, TUserHandledMessage> : IInternalHandler, IHandler<TReceivedMessage>
Done

2022-03-18 10:40 UTC, DavidRamsbottomRTGS commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK/Subscriber/HandleMessageCommands/HandleMessageCommandsFactory.cs
> +		var internalCommands = _internalCommandCreators.Select(creator => creator.Create(_internalHandlers.ToList(), userHandlers));
Went with option B - seems a lot neater and better use of interfaces.

2022-03-18 10:41 UTC, DavidRamsbottomRTGS commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK/Subscriber/Messages/IdCryptCreateInvitationNotificationV1.cs
> +public record IdCryptCreateInvitationNotificationV1
Added

2022-03-18 10:41 UTC, DavidRamsbottomRTGS commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/InternalMessages/IdCryptInvitationV1.cs
> +public record IdCryptInvitationV1
Agreed - created a common one for all tests to use.

2022-03-18 10:42 UTC, DavidRamsbottomRTGS commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK/Subscriber/Handlers/Internal/IdCryptCreateInvitationRequestV1Handler.cs
> +	{
I initially didn't do this as I figured it was all internal like you say and there should be no way of this happening.  Also there would be no way of having that condition under test (as the handler is internal).  I was in 2 minds about it however so have now added it.  Can't hurt!

2022-03-18 10:42 UTC, DavidRamsbottomRTGS commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK/Subscriber/Handlers/Internal/IdCryptCreateInvitationRequestV1Handler.cs
> +			_logger.LogDebug("Sent CreateInvitation request to ID Crypt Cloud Agent");
Updated these logs and the equivalent ones in RtgsConnectionBroker

2022-03-18 10:43 UTC, DavidRamsbottomRTGS commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK/Subscriber/Handlers/Internal/IdCryptCreateInvitationRequestV1Handler.cs
> +		var agentPublicDid = await GetIdCryptAgentPublicDidAsync();
Yes and no - it would leave an open invitation on the agent which matters in the sense that it would become redundant.  It wouldn't cause any 'harm' though.  In the past we have decided to ignore this kind of thing for now and think more carefully about it (and other resilience matters) in a future iteration.

2022-03-18 10:44 UTC, DavidRamsbottomRTGS commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/InternalHandlers/GivenOpenSubscriberConnection.cs
> +	public class AndIdCryptApiAvailable : IAsyncLifetime, IClassFixture<GrpcServerFixture>
Agreed - copy and paste laziness.  Updated this and the other test classes which didn't need it.

2022-03-18 11:23 UTC, lewishenson requested changes

2022-03-18 11:23 UTC, lewishenson commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/InternalHandlers/GivenOpenSubscriberConnection.cs
> +public class GivenOpenSubscriberConnection
Not sure about the name - are we expecting all internal handler integration tests to go here?

2022-03-18 11:23 UTC, lewishenson commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/InternalHandlers/GivenOpenSubscriberConnection.cs
> +			errorLogs.Message.Should().Be(expectedErrorLogMessage);
Might throw an unexpected exception as SingleOrDefault could return the default (null).

Could probably use FluentAssertion's methods more directly (i.e. replace SingleOrDefault with Should()...)

2022-03-18 11:23 UTC, lewishenson commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/InternalHandlers/GivenOpenSubscriberConnection.cs
> +
Blank line that can be removed

2022-03-18 11:23 UTC, lewishenson commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/InternalHandlers/GivenOpenSubscriberConnection.cs
> +
Blank line that can be removed

2022-03-18 11:23 UTC, lewishenson commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/InternalHandlers/GivenOpenSubscriberConnection.cs
> +
Blank line that can be removed

2022-03-18 11:23 UTC, lewishenson commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/InternalHandlers/GivenOpenSubscriberConnection.cs
> +			var errorLogs = _serilogContext.LogsFor(
Same comments as previous test

2022-03-18 12:15 UTC, DavidRamsbottomRTGS commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/InternalHandlers/GivenOpenSubscriberConnection.cs
> +				.Single();
Agreed - updated

2022-03-18 12:17 UTC, DavidRamsbottomRTGS commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/InternalHandlers/GivenOpenSubscriberConnection.cs
> +			var inviteRequestQueryParams = QueryHelpers.ParseQuery(_idCryptMessageHandler.Requests[IdCryptEndPoints.InvitationPath].RequestUri?.Query);
Played around with this a bit, but felt the exception we got when the key was missing was actually more helpful.  I had to write quite a few more lines of code to get the information given in the missing key exception.

2022-03-18 12:18 UTC, DavidRamsbottomRTGS commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/InternalHandlers/GivenOpenSubscriberConnection.cs
> +public class GivenOpenSubscriberConnection
We discussed this and figured that it would need refactoring if/when more internal handlers were added and trying to pre-empt what would be required at this point was perhaps YAGNI.  Didn't consider just naming it better tho!  Updated class name to GivenIdCryptCreateInvitationSentToOpenSubscriberConnection

2022-03-18 12:18 UTC, DavidRamsbottomRTGS commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/InternalHandlers/GivenOpenSubscriberConnection.cs
> +			var expectedErrorLogMessage = "Error occurred when sending GetPublicDid request to ID Crypt Cloud Agent";
Inlined

2022-03-18 12:18 UTC, DavidRamsbottomRTGS commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/InternalHandlers/GivenOpenSubscriberConnection.cs
> +			var errorLogs = _serilogContext.LogsFor("RTGS.DotNetSDK.Subscriber.Handlers.Internal.IdCryptCreateInvitationRequestV1Handler", LogEventLevel.Error).SingleOrDefault();
Removed names altogether as just 'fluented' off the value returned from LogsFor

2022-03-18 12:19 UTC, DavidRamsbottomRTGS commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/InternalHandlers/GivenOpenSubscriberConnection.cs
> +			errorLogs.Message.Should().Be(expectedErrorLogMessage);
Fixed

2022-03-18 12:19 UTC, DavidRamsbottomRTGS commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/InternalHandlers/GivenOpenSubscriberConnection.cs
> +
Fixed

2022-03-18 12:19 UTC, DavidRamsbottomRTGS commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/InternalHandlers/GivenOpenSubscriberConnection.cs
> +
Fixed

2022-03-18 12:19 UTC, DavidRamsbottomRTGS commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/InternalHandlers/GivenOpenSubscriberConnection.cs
> +
Fixed

2022-03-18 12:19 UTC, DavidRamsbottomRTGS commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/InternalHandlers/GivenOpenSubscriberConnection.cs
> +			var errorLogs = _serilogContext.LogsFor(
Fixed in same way

2022-03-18 15:17 UTC, lewishenson commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/InternalHandlers/GivenOpenSubscriberConnection.cs
> +				.Single();
Got an used variable leftover, I'll remove it and push.

2022-03-18 15:21 UTC, lewishenson approved these changes

2022-03-18 15:24 UTC, sichiu approved these changes

2022-03-18 15:34 UTC, merged