Feature/3473 consistent naming
RTGS-OpenSource/rtgs-dotnet-sdk pull request #68
Opened 2022-03-28 17:12 UTC by manishkulkarni

2022-03-29 08:47 UTC, lewishenson commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK/Subscriber/Messages/BankPartnersResponseV1.cs
> +		public string Currency { get; init; }
Slightly confused with the inconsistency - keeping `DbtrAgtAcct` as it's an ISO20022 term but so is Ccy for Currency.

2022-03-30 09:11 UTC, zpbd commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK/Publisher/Messages/UpdateLedgerRequestV1.cs
>  	/// IBAN (International Bank Account Number).
No longer just an IBAN

2022-03-30 09:16 UTC, zpbd commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK/Subscriber/Messages/BankPartnersResponseV1.cs
> +	public IEnumerable<BankPartner> BnkPrtnrs { get; init; }
I know it was already missing, but whilst we are here is it worth adding documentation for each of these properties too?

2022-03-30 09:21 UTC, zpbd commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK/Publisher/Messages/AtomicLockRequestV1.cs
>  	/// Creditor amount - describes the value and currency of the transfer.
Now that we are using abbreviations everywhere, I think it would be nice to prefix all of our XML summaries with the full unabbreviated name.

e.g. for `UltmtCdtrAmt`:  `"UltimateCreditorAmount - describes the value and currency of the transfer."`

or for `Sccs`: `"Success - True to confirm, false otherwise."`

In the same way that the ISO standard defines all of their properties with an unabbreviated name.

2022-03-31 10:39 UTC, chris-brown approved these changes

2022-03-31 10:40 UTC, chris-brown commented
@lewishenson can you review pls 📑

2022-03-31 10:53 UTC, lewishenson requested changes

2022-03-31 10:53 UTC, lewishenson commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/TestData/ValidMessages.cs
> -	public static readonly ISO20022.Messages.Pacs_008_001.V10.FIToFICustomerCreditTransferV10 PayawayFunds = new()
Would prefer to leave the namespace inline as we've got other message types in this class and you could potentially see clashes (e.g. ActiveCurrencyAndAmount appears in multiple namespaces).

2022-03-31 11:50 UTC, manishkulkarni commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/TestData/ValidMessages.cs
> -	public static readonly ISO20022.Messages.Pacs_008_001.V10.FIToFICustomerCreditTransferV10 PayawayFunds = new()
sure, I have reverted back to inline namespaces

2022-03-31 11:50 UTC, manishkulkarni commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK/Subscriber/Messages/BankPartnersResponseV1.cs
> +	public IEnumerable<BankPartner> BnkPrtnrs { get; init; }
done

2022-03-31 11:51 UTC, manishkulkarni commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK/Publisher/Messages/AtomicLockRequestV1.cs
>  	/// Creditor amount - describes the value and currency of the transfer.
done

2022-03-31 11:59 UTC, lewishenson approved these changes

2022-03-31 12:53 UTC, merged