#3538 - Verify PayawayCreate messages
RTGS-OpenSource/rtgs-dotnet-sdk pull request #80
Opened 2022-04-19 14:37 UTC by DavidRamsbottomRTGS

2022-04-20 13:22 UTC, DavidRamsbottomRTGS commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/GivenOpenConnection.cs
> +	private static readonly TimeSpan WaitForReceivedMessageDuration = TimeSpan.FromMilliseconds(1000);
Shall we revert this back to 100?

2022-04-20 13:22 UTC, DavidRamsbottomRTGS commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/GivenOpenConnection.cs
> +		var errorLogs = _serilogContext.SubscriberLogs(LogEventLevel.Error);
Don't need this temporary code anymore

2022-04-20 13:22 UTC, DavidRamsbottomRTGS commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/Verification/GivenOpenConnection/WhenVerificationIsSuccessful.cs
> +
Empty line

2022-04-20 13:22 UTC, DavidRamsbottomRTGS commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK/Subscriber/IdCrypt/Verification/PayawayFundsMessageVerifier.cs
> +		if (privateSignature is null || alias is null)
We were going to do is null or empty here and add tests

2022-04-20 13:30 UTC, josephreillyltd commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/GivenOpenConnection.cs
> +		var errorLogs = _serilogContext.SubscriberLogs(LogEventLevel.Error);
don't think we still need this assertion about errors

2022-04-20 13:34 UTC, DavidRamsbottomRTGS commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/GivenOpenConnection.cs
> +			{ "public-did-signature", "public-did-signature" },
I think it's legit to keep it here - the header will be on the message after all, we just don't care about it in the verifier we have been working with.  It's still correct to add all 3 headers to our test messages in my opinion.

2022-04-20 13:40 UTC, josephreillyltd commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/Verification/GivenOpenConnection/WhenVerificationIsSuccessful.cs
> +﻿using System.Text.Json;
We aren't testing any logging in this file

2022-04-26 14:58 UTC, sichiu commented
Hold off merging this in for now. We've had to add a feature toggle to the signing stuff so it doesn't break E2E tests. Will need the same doing for this.

2022-04-26 15:24 UTC, Bassetts requested changes

2022-04-26 15:24 UTC, Bassetts commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/TestData/SubscriberActions.cs
> +	};
```suggestion
	private static readonly Dictionary<string, string> DefaultSigningHeaders = new()
	{
		{ "public-did-signature", "public-did-signature" },
		{ "pairwise-did-signature", "pairwise-did-signature" },
		{ "alias", "alias" }
	};
```

2022-04-26 15:24 UTC, Bassetts commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/TestData/SubscriberActions.cs
> +		new(new AllTestHandlers(), handlers => handlers.OfType<TestPayawayFundsV1Handler>().Single(), "PayawayFunds", ValidMessages.PayawayFunds, _defaultSigningHeaders);
If you implement the above suggestion...

```suggestion
		new(new AllTestHandlers(), handlers => handlers.OfType<TestPayawayFundsV1Handler>().Single(), "PayawayFunds", ValidMessages.PayawayFunds, DefaultSigningHeaders);
```

2022-04-26 15:24 UTC, Bassetts commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/Verification/GivenOpenConnection/AndIdCryptVerifyConnectionDidApiIsNotAvailable.cs
> +		raisedException.Should().BeOfType<IdCryptException>().Which.Message.Should().Be($"Error verifying private signature");
```suggestion
		raisedException.Should().BeOfType<IdCryptException>().Which.Message.Should().Be("Error verifying private signature");
```

2022-04-26 15:24 UTC, Bassetts commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/Verification/GivenOpenConnection/AndSignaturesAreNotValid.cs
> +		_rtgsSubscriber.OnExceptionOccurred += (_, args) => exceptionSignal.Set();
```suggestion
		_rtgsSubscriber.OnExceptionOccurred += (_, _) => exceptionSignal.Set();
```

2022-04-26 15:24 UTC, Bassetts commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/Verification/GivenOpenConnection/AndSignaturesAreValid.cs
> +			.Single().Content.ReadAsStringAsync();
```suggestion
		var requestContent = await _idCryptMessageHandler.Requests[VerifyPrivateSignatureSuccessfully.Path]
			.Single().Content?.ReadAsStringAsync();
```
#nitpick

2022-04-26 15:24 UTC, Bassetts commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/Verification/GivenOpenConnection/AndSignaturesAreValid.cs
> +		signDocumentRequest.ConnectionId.Should().Be(GetActiveConnectionWithAlias.ExpectedResponse.ConnectionId);
```suggestion
		signDocumentRequest!.ConnectionId.Should().Be(GetActiveConnectionWithAlias.ExpectedResponse.ConnectionId);
```
#nitpick

2022-04-26 15:24 UTC, Bassetts commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/Verification/GivenOpenConnection/AndSignaturesAreValid.cs
> +			.Single().Content.ReadAsStringAsync();
```suggestion
		var requestContent = await _idCryptMessageHandler.Requests[VerifyPrivateSignatureSuccessfully.Path]
			.Single().Content!.ReadAsStringAsync();
```

2022-04-26 15:24 UTC, Bassetts commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/Verification/GivenOpenConnection/AndSignaturesAreValid.cs
> +		signDocumentRequest.Signature.Should().Be(expectedPrivateSignature);
```suggestion
		signDocumentRequest!.Signature.Should().Be(expectedPrivateSignature);
```

2022-04-26 15:24 UTC, Bassetts commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/Verification/GivenOpenConnection/AndSignaturesAreValid.cs
> +			.Single().Content.ReadAsStringAsync();
```suggestion
		var requestContent = await _idCryptMessageHandler.Requests[VerifyPrivateSignatureSuccessfully.Path]
			.Single().Content!.ReadAsStringAsync();
```

2022-04-26 15:24 UTC, Bassetts commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/Verification/GivenOpenConnection/AndSignaturesAreValid.cs
> +		signDocumentRequest.Document.Should().BeEquivalentTo(subscriberAction.Message);
```suggestion
		signDocumentRequest!.Document.Should().BeEquivalentTo(subscriberAction.Message);
```

2022-04-26 15:24 UTC, Bassetts commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/Verification/GivenOpenConnection/AndSigningHeadersAreMissing.cs
> +		var signingHeaders = new Dictionary<string, string>()
```suggestion
		var signingHeaders = new Dictionary<string, string>
```

2022-04-26 15:24 UTC, Bassetts commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/Verification/GivenOpenConnection/AndSigningHeadersAreMissing.cs
> +		var signingHeaders = new Dictionary<string, string>()
```suggestion
		var signingHeaders = new Dictionary<string, string>
```

2022-04-26 15:24 UTC, Bassetts commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/Verification/GivenOpenConnection/AndSigningHeadersAreMissing.cs
> +		var signingHeaders = new Dictionary<string, string>()
```suggestion
		var signingHeaders = new Dictionary<string, string>
```

2022-04-26 15:24 UTC, Bassetts commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/Verification/GivenOpenConnection/AndSigningHeadersAreMissing.cs
> +		var signingHeaders = new Dictionary<string, string>()
```suggestion
		var signingHeaders = new Dictionary<string, string>
```

2022-04-26 15:24 UTC, Bassetts commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/Verification/GivenOpenConnection/AndSigningHeadersAreMissing.cs
> +		var signingHeaders = new Dictionary<string, string>()
```suggestion
		var signingHeaders = new Dictionary<string, string>
```

2022-04-26 15:24 UTC, Bassetts commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/Verification/GivenOpenConnection/AndSigningHeadersAreMissing.cs
> +		var signingHeaders = new Dictionary<string, string>()
```suggestion
		var signingHeaders = new Dictionary<string, string>
```

2022-04-26 15:24 UTC, Bassetts commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/Verification/GivenOpenConnection/AndSigningHeadersAreMissing.cs
> +		var signingHeaders = new Dictionary<string, string>()
```suggestion
		var signingHeaders = new Dictionary<string, string>
```

2022-04-26 15:24 UTC, Bassetts commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/Verification/GivenOpenConnection/AndSigningHeadersAreMissing.cs
> +		var signingHeaders = new Dictionary<string, string>()
```suggestion
		var signingHeaders = new Dictionary<string, string>
```

2022-04-26 15:24 UTC, Bassetts commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/Verification/GivenOpenConnection/AndSigningHeadersAreMissing.cs
> +	public async Task WhenAliasHeaderMissing_WhenVerifyingMessage_ThenLogError<TMessage>(SubscriberAction<TMessage> subscriberAction)
Should this be `And` instead of `When`?

```suggestion
	public async Task AndAliasHeaderMissing_WhenVerifyingMessage_ThenLogError<TMessage>(SubscriberAction<TMessage> subscriberAction)
```

2022-04-26 15:24 UTC, Bassetts commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/Verification/GivenOpenConnection/AndSigningHeadersAreMissing.cs
> +	public async Task WhenAliasHeaderMissing_WhenVerifyingMessage_ThenRaiseExceptionEvent<TMessage>(SubscriberAction<TMessage> subscriberAction)
```suggestion
	public async Task AndAliasHeaderMissing_WhenVerifyingMessage_ThenRaiseExceptionEvent<TMessage>(SubscriberAction<TMessage> subscriberAction)
```

2022-04-26 15:24 UTC, Bassetts commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/Verification/GivenOpenConnection/AndSigningHeadersAreMissing.cs
> +	public async Task WhenPrivateSignatureHeaderMissing_WhenVerifyingMessage_ThenRaiseExceptionEvent<TMessage>(SubscriberAction<TMessage> subscriberAction)
```suggestion
	public async Task AndPrivateSignatureHeaderMissing_WhenVerifyingMessage_ThenRaiseExceptionEvent<TMessage>(SubscriberAction<TMessage> subscriberAction)
```

2022-04-26 15:24 UTC, Bassetts commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/Verification/GivenOpenConnection/AndSigningHeadersAreMissing.cs
> +	public async Task WhenPrivateDidHeaderEmpty_WhenVerifyingMessage_ThenLogError<TMessage>(SubscriberAction<TMessage> subscriberAction)
```suggestion
	public async Task AndPrivateDidHeaderEmpty_WhenVerifyingMessage_ThenLogError<TMessage>(SubscriberAction<TMessage> subscriberAction)
```

2022-04-26 15:24 UTC, Bassetts commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/Verification/GivenOpenConnection/AndSigningHeadersAreMissing.cs
> +	public async Task WhenAliasHeaderEmpty_WhenVerifyingMessage_ThenLogError<TMessage>(SubscriberAction<TMessage> subscriberAction)
```suggestion
	public async Task AndAliasHeaderEmpty_WhenVerifyingMessage_ThenLogError<TMessage>(SubscriberAction<TMessage> subscriberAction)
```

2022-04-26 15:24 UTC, Bassetts commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/Verification/GivenOpenConnection/AndSigningHeadersAreMissing.cs
> +	public async Task WhenPrivateSignatureHeaderEmpty_WhenVerifyingMessage_ThenRaiseExceptionEvent<TMessage>(SubscriberAction<TMessage> subscriberAction)
```suggestion
	public async Task AndPrivateSignatureHeaderEmpty_WhenVerifyingMessage_ThenRaiseExceptionEvent<TMessage>(SubscriberAction<TMessage> subscriberAction)
```

2022-04-26 15:24 UTC, Bassetts commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK.IntegrationTests/Subscriber/Verification/GivenOpenConnection/AndSigningHeadersAreMissing.cs
> +	public async Task WhenAliasHeaderEmpty_WhenVerifyingMessage_ThenRaiseExceptionEvent<TMessage>(SubscriberAction<TMessage> subscriberAction)
```suggestion
	public async Task AndAliasHeaderEmpty_WhenVerifyingMessage_ThenRaiseExceptionEvent<TMessage>(SubscriberAction<TMessage> subscriberAction)
```

2022-04-26 15:24 UTC, Bassetts commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK/Subscriber/IdCrypt/Verification/IVerifyMessage.cs
> +		CancellationToken cancellationToken = default);
```suggestion
	Task VerifyMessageAsync(RtgsMessage rtgsMessage, CancellationToken cancellationToken = default);
```
#nitpick

2022-04-27 08:58 UTC, Bassetts commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK/Subscriber/IdCrypt/Verification/PayawayFundsMessageVerifier.cs
> +
This has been done https://github.com/RTGS-OpenSource/rtgs-dotnet-sdk/pull/80/commits/5b856beef4eedc87956f46a8d6330f8966c5ceb3#diff-3c5306e50d87a5539242122799cef88045085cf4371e349ddcae57f5b2d4601a

2022-04-27 09:52 UTC, Bassetts approved these changes

2022-04-27 10:52 UTC, merged