Use RTGS.global Id instead of Did
RTGS-OpenSource/rtgs-dotnet-sdk pull request #81
Opened 2022-04-21 12:24 UTC by lewishenson

Non-breaking changes for messages that are sent to/from RTGS - hence duplicate properties or headers. Will allow the changes to be gradually rolled out.

Breaking changes for SDK-specific items, e.g. the options. When new version of the package is published, apps can be simply updated to use the renamed properties.

2022-04-22 12:58 UTC, chris-brown requested changes

2022-04-22 12:58 UTC, chris-brown commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK/Publisher/IdCrypt/IdCryptPublisher.cs
> +		var headers = new Dictionary<string, string> { { "bankpartnerdid", bankPartnerRtgsGlobalId }, { "bank-partner-rtgs-global-id", bankPartnerRtgsGlobalId } };
I vote for Pascal Kebab case

2022-04-22 12:58 UTC, chris-brown commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK/Publisher/IdCrypt/Messages/IdCryptBankInvitationNotificationV1.cs
>  	public string BankPartnerDid { get; init; }
can deprecate this property with xml docs.

2022-04-22 12:58 UTC, chris-brown commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK/Publisher/IdCrypt/Messages/IdCryptBankInvitationNotificationV1.cs
>  	public string BankPartnerDid { get; init; }
helping with removing it

2022-04-22 12:58 UTC, chris-brown commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK/Publisher/InternalPublisher.cs
>  			_toRtgsCall = _paymentClient.ToRtgsMessage(grpcCallHeaders, cancellationToken: CancellationToken.None);
Same as headers for RtgsMessage. I vote for Pascal-Kebab case

2022-04-25 16:56 UTC, lewishenson commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK/Publisher/IdCrypt/IdCryptPublisher.cs
> +		var headers = new Dictionary<string, string> { { "bankpartnerdid", bankPartnerRtgsGlobalId }, { "bank-partner-rtgs-global-id", bankPartnerRtgsGlobalId } };
Agreed

2022-04-25 16:56 UTC, lewishenson commented on src/RTGS.DotNetSDK/RTGS.DotNetSDK/Publisher/IdCrypt/Messages/IdCryptBankInvitationNotificationV1.cs
>  	public string BankPartnerDid { get; init; }
No longer applicable as switching to a breaking change approach.

2022-04-26 10:35 UTC, chris-brown approved these changes

2022-04-26 13:30 UTC, lewishenson commented
Change of approach, now going with breaking changes.

2022-04-26 13:34 UTC, merged